enabled_fonts:
  - 'local_fonts://voltage'
  - 'local_fonts://voltage_bold'
  - 'local_fonts://voltage_thin'
load_all_enabled_fonts: 1
load_on_themes: {  }
_core:
  default_config_hash: TghDxAeHu4gER0JZhzPbMawpRgxggVsIu54oyTeaJOo
