_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 794b3f92-c447-450e-bec9-3b6cab6d8585
name: 'Mirror Twin Brewing'
mail: info@mirrortwinbrewing.com
slogan: ''
page:
  403: /node/228
  404: /node/227
  front: /node/1
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: no-reply@mirrortwinbrewing.com
